---
title: "Curso"
author:
- name: Haline Dugolin Ceccato
date:
  month: Março
  year: 2022
header-includes:
 - \usepackage{bbm}
 - \usepackage{times}
 - \usepackage{setspace}
 - \onehalfspacing
 - \usepackage{lscape}
 - \usepackage{indentfirst}
 - \usepackage[brazil]{babel}
 - \usepackage{graphicx,psfrag}
 - \usepackage[T1]{fontenc}
 - \usepackage{times, amsmath, amsfonts, amssymb, amsthm}
 - \usepackage{xcolor}
 - \usepackage{url}
 - \usepackage[skip=2pt,size=normalsize]{caption}
 - \captionsetup{labelsep=endash, format=hang, width=\textwidth} 
 - \usepackage{placeins}
 - \usepackage[labelfont=bf]{caption}
 - \usepackage{sectsty}
 - \sectionfont{\fontsize{12}{15}\selectfont}
 - \subsectionfont{\fontsize{12}{15}\selectfont}
 - \usepackage{enumitem}
 - \usepackage{float}
 - \floatplacement{figure}{H}
 - \floatplacement{table}{H}
 - \linespread{1.5}
 - \usepackage{fancyhdr}
 - \pagestyle{fancy}
 - \lhead{}
 - \chead{}
 - \rhead{\thepage}
 - \lfoot{}
 - \cfoot{}
 - \rfoot{}
 - \renewcommand{\headrulewidth}{0pt}
 - \addto\captionsbrazil{\renewcommand{\contentsname}{}}
 - \addto\captionsbrazil{\renewcommand{\listfigurename}{}}
 - \addto\captionsbrazil{\renewcommand{\listtablename}{}}
 - \addto\captionsbrazil{\renewcommand{\bibname}{}}
output: pdf_document
keep_tex: true
fontsize: 12pt
geometry: margin=1in
spacing: onehalfspacing 
endnote: no
editor_options: 
  chunk_output_type: console
---

```{r setupall, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r child = 'teoria_semana1.Rmd'}
```

```{r child = 'hora_do_recreio_semana1.Rmd'}
```

```{r child = 'desafio_semana1.Rmd'}
```