---
title:
header-includes:
 - \usepackage{bbm}
 - \usepackage{times}
 - \usepackage{setspace}
 - \onehalfspacing
 - \usepackage{lscape}
 - \usepackage{indentfirst}
 - \usepackage[brazil]{babel}
 - \usepackage{graphicx,psfrag}
 - \usepackage[T1]{fontenc}
 - \usepackage{times, amsmath, amsfonts, amssymb, amsthm}
 - \usepackage{xcolor}
 - \usepackage{url}
 - \usepackage[skip=2pt,size=normalsize]{caption}
 - \captionsetup{labelsep=endash, format=hang, width=\textwidth} 
 - \usepackage{placeins}
 - \usepackage[labelfont=bf]{caption}
 - \usepackage{sectsty}
 - \sectionfont{\fontsize{12}{15}\selectfont}
 - \subsectionfont{\fontsize{12}{15}\selectfont}
 - \usepackage{enumitem}
 - \usepackage{float}
 - \floatplacement{figure}{H}
 - \floatplacement{table}{H}
 - \linespread{1.5}
 - \usepackage{fancyhdr}
 - \pagestyle{fancy}
 - \lhead{}
 - \chead{}
 - \rhead{\thepage}
 - \lfoot{}
 - \cfoot{}
 - \rfoot{}
 - \renewcommand{\headrulewidth}{0pt}
 - \addto\captionsbrazil{\renewcommand{\contentsname}{}}
 - \addto\captionsbrazil{\renewcommand{\listfigurename}{}}
 - \addto\captionsbrazil{\renewcommand{\listtablename}{}}
 - \addto\captionsbrazil{\renewcommand{\bibname}{}}
output: pdf_document
keep_tex: true
fontsize: 12pt
geometry: margin=1in
spacing: onehalfspacing 
endnote: no
editor_options: 
  chunk_output_type: console
---

\newpage
\thispagestyle{empty}
\begin{singlespace}
\noindent \uppercase{Primeira Semana - Hora do Recreio}, o desafio apresentado consiste em desenvolver um programa que:  

* Pergunte o nome e o sobrenome do usuário; e,  

* Escreva o nome completo do usuário  

\newpage

#1. Seção Hora do Recreio (Aula)

```{r}
#cat
cat("Bom dia!", "\n") #\n significa escrever o texto seguinte em uma nova linha

a=10
b="Gigio"
cat(b, "tem", a, "anos", "\n")

#redline 
texto = readline("Quantos anos você tem?")
cat("Você tem", texto, "anos")

```


#2. Desafio da hora do recreio 

```{r}
nome = readline("Qual o seu nome?")
sobrenome = readline("Qual o seu sobrenome?")
cat("Voce é", nome, sobrenome)
```

#3. Desafio desenvolvido pelo professor  

```{r}
cat("Qual é o seu nome?")
nome = readline("Digite o seu nome:")

cat("Qual o seu sobrenome?")
sobrenome = readline("Digite o seu sobrenome:")

cat("O seu nome completo é:", nome, "", sobrenome)
```

